version: '3.8'
# transcription stream startup
#
# make sure the volumes exist
services:

# Start up the worker container
  ts-gpu:
    image: ts-gpu:latest
    build:
      context: ts-gpu
      dockerfile: Dockerfile
    environment:
      - DIARIZATION_MODEL=${DIARIZATION_MODEL}
      - TRANSCRIPTION_MODEL=${TRANSCRIPTION_MODEL}
      - MAX_CONCURRENT_TRANSFORMS=${MAX_CONCURRENT_TRANSFORMS}
      - MAX_CONCURRENT_SUMMARYS=${MAX_CONCURRENT_SUMMARYS}
      - OLLAMA_ENDPOINT=${OLLAMA_ENDPOINT}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    shm_size: 6gb
    ports:
      - "22222:22"
    volumes:
      - transcriptionstream:/transcriptionstream
      - transcriptionstream:/home/transcriptionstream
#      - transcriptionstream-scripts:/root/scripts

    networks:
      - default

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

# Start up the web front end
  ts-web:
    build:
      context: ts-web
      dockerfile: Dockerfile
    environment:
      - TS_WEB_SECRET_KEY=${TS_WEB_SECRET_KEY}
    ports:
      - "5006:5000"
    volumes:
      - transcriptionstream:/transcriptionstream
    networks:
      - default

# Start up MeiliSearch
  ts-meilisearch:
    image: getmeili/meilisearch
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      # - MEILI_HTTP_CORS_ORIGINS=http://172.30.1.11:5000
      - MEILI_NO_ANALYTICS=true 
    ports:
      - "7700:7700"
    volumes:
      - transcriptionstream:/transcriptionstream
      - transcriptionstream:/meili_data
    networks:
      - default



# if you want to run ollama locally and have enough vram uncomment this section
#  # Startup ts-gpt
  # ts_gpt_service:
  #   image: ollama/ollama
  #   container_name: ts-gpt
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - transcriptionstream:/root/.ollama
  #   networks:
  #     ts_private_network:
  #       ipv4_address: 172.30.1.3

  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]


volumes:
  transcriptionstream:
#  transcriptionstream-scripts:
#    external: true

